title = "SMN Robotics"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"

# Automatically makes sections show up in the menu
#SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

# render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  site_logo = "/img/937-logo-transparent.webp"
  footer_image = "/img/937-numbers-transparent.webp"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-red"
  #recent_posts_number = 2

  custom_css = ["css/custom.css"]
  
  # Social links
  github = "https://github.com/frc937/"
